name: fatescal-env
channels:
  - conda-forge
  - defaults
dependencies:
  - dask=2023.3.0
  - flox=0.7.2
  - jupyterlab=3.6.1
  - matplotlib=3.7.0
  - nc-time-axis=1.4.1
  - netcdf4=1.6.3
  - numpy=1.24.2
  - pandas=1.5.3
  - pip=23.0.1
  - python=3.11.0
  - py-xgboost=1.7.6
  - scipy=1.10.1
  - seaborn=0.13.0
  - shap=0.42.1
  - xarray=2023.3.0
  - pip:
    - -e .
    - scikeras==0.11.0
    - scikit-learn==1.2.2
    - properscoring==0.1
    - geopandas==0.14.1
